### PR TITLE
Fixup documentation for file handling and ensure last record isn't dropped.

### PR DESCRIPTION
**Pull request by HuwCampbell**
Fix final record handling when it's not terminated by a new line. It would be incorrectly dropped.

The code used to contain a bug where the final empty string (and its effect) was read twice, this caused a read after close from readFile when it was accessed the second time due to it eagerly closing.

This issue was fixed and readFile is fine; unfortunately it introduced a bug where the final entry could be dropped if the file doesn't end in a new line. The solution is to provide the parser with an empty bytestring / bytestream (but crucially, not the effect).

### CODE REVIEW

**Comment by HuwCampbell** [comment]
Ping @ivan-m

**Comment by HuwCampbell** [comment]
@chessai ?

**Comment by HuwCampbell** [comment]
So I think this issue is pretty serious as it's silently dropping the final record of valid CSV files.

Is anyone maintaining this (do they need help?).

**Comment by HuwCampbell** [comment]
Ping.

@fosskers? Does anyone have access to this repo?

**Comment by chessai** [comment]
@HuwCampbell Sorry, May was a very busy month for me.

Do the tests pass? I don't think we have CI set up on this repo.

**Comment by HuwCampbell** [comment]
image

**Comment by HuwCampbell** [comment]
Thanks.
No worries.

**Pull request merged**
